[package]
name = "capi-virtual"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos.workspace = true 
web-sys.workspace = true
send_wrapper.workspace = true

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
